### ISSUE TITLE
error...

### ISSUE THREAD

**Issue by runtimevic** [HackSoftware/django_mkdocs#1]
Hello, how solve error???

(.venv) C:\Users\Runtimevic\source\repos\django_mkdocs>mkdocs build
Traceback (most recent call last):
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\mkdocs\config\config_options.py", line 366, in walk_docs_dir
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Runtimevic\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Runtimevic\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Runtimevic\source\repos\django_mkdocs\myproject\.venv\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\mkdocs\__main__.py", line 150, in build_command
    build.build(config.load_config(
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\mkdocs\config\base.py", line 181, in load_config
    errors, warnings = cfg.validate()
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\mkdocs\config\base.py", line 105, in validate
    post_failed, post_warnings = self._post_validate()
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\mkdocs\config\base.py", line 85, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "c:\users\runtimevic\source\repos\django_mkdocs\myproject\.venv\lib\site-packages\mkdocs\config\config_options.py", line 391, in post_validation
    for filename in self.walk_docs_dir(config['docs_dir']):
RuntimeError: generator raised StopIteration

**Comment by RadoRado** [comment]
@runtimevic Hello :wave: 

This project is not-supported for at least 6 years.

Cheers!
